version: '3.5'
services:
  milog-mysql:
    image: mysql:latest
    container_name: "milog-mysql"
    volumes:
      - "./docker/config/mysql:/etc/mysql/conf.d"
      - "./docker/data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3923:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: milog
    networks:
      - "milog-network"
  milog-phpfpm:
    image: chrsc/php-fpm-laravel:latest
    container_name: "milog-phpfpm"
    depends_on:
      - milog-mysql
    volumes:
      - "./:/var/www/"
      - "./docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    restart: always
    networks:
      - milog-network
  milog-nginx:
    image: nginx:1.17-alpine
    container_name: "milog-nginx"
    depends_on:
      - milog-phpfpm
    ports:
      - "8980:80"
      - "8943:443"
    volumes:
      - "./:/var/www/"
      - "./docker/config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/certs:/etc/nginx/certs"
      - "./docker/logs/nginx:/var/log/nginx"
    restart: always
    networks:
      - "milog-network"
  milog-redis:
    image: redis:5.0.6-alpine
    container_name: "milog-redis"
    depends_on:
      - "milog-phpfpm"
    volumes:
      - "./docker/data/redis:/data"
      - "./docker/config/redis.conf:/usr/local/etc/redis/redis.conf"
    restart: always
    networks:
      - "milog-network"
networks:
  milog-network:
    name: "custom-milog-network"
