services:
  milog-postgres:
    image: postgres:17-alpine
    container_name: "milog-postgres"
    volumes:
      - "./docker/data/postgres:/var/lib/postgresql/data"
      - "./docker/postgres/init:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - "3923:5432"
    environment:
      POSTGRES_DB: milog
      POSTGRES_USER: milog
      POSTGRES_PASSWORD: password
    networks:
      - "milog-network"
  milog-phpfpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    image: milog-php-fpm:8.5
    container_name: "milog-phpfpm"
    depends_on:
      - milog-postgres
    volumes:
      - "./:/var/www/"
      - "./docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: milog-postgres
      DB_PORT: 5432
      DB_DATABASE: milog
      DB_USERNAME: milog
      DB_PASSWORD: password
    restart: always
    networks:
      - milog-network
  milog-nginx:
    image: nginx:1.17-alpine
    container_name: "milog-nginx"
    depends_on:
      - milog-phpfpm
    ports:
      - "8980:80"
      - "8943:443"
    volumes:
      - "./:/var/www/"
      - "./docker/config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/certs:/etc/nginx/certs"
      - "./docker/logs/nginx:/var/log/nginx"
    restart: always
    networks:
      - "milog-network"
  milog-redis:
    image: redis:5.0.6-alpine
    container_name: "milog-redis"
    depends_on:
      - "milog-phpfpm"
    volumes:
      - "./docker/data/redis:/data"
      - "./docker/config/redis.conf:/usr/local/etc/redis/redis.conf"
    restart: always
    networks:
      - "milog-network"
networks:
  milog-network:
    name: "custom-milog-network"
